### ISSUE TITLE
cardCounterRestore() isnt checking against my_deck_cards[idx]

### ISSUE THREAD

**Issue by versvs** [hugojcastro/HearthStoneHelper#3]
Hi,

I just noticed that when I add cards back to the deck (because I misclicked the wrong card, or because I Entomb a card from my opponent that happened to be also in my starting list) the counter can get back to 30.

The card itself is not being added beyond the limit set by the starting deck list, but the counter goes up to 30. If you right-click any card, the counter is always updated (cards_remain++).

I'm an awful JS programmer, so I think I was able to spot the problem, but couldn't come with a solution in the form of a pull request just yet.

Thanks again! :)

**Comment by versvs** [comment]
More info: it seems the problem only appears when we try to add a second copy of a card that had only 1 copy in the initial deck list :)

**Comment by hugojcastro** [comment]
ah, damn... I didn't catch it at first, but I'm able to reproduce it now.
Yeah, when restoring cards it does the adition before checking if it's possible or not. In the second case, card is not restored but card count is incorrectly updated. A fix is on the way :)

Thanks a lot for the report :+1: ^^

Btw... Didn't take into account _Entomb_ card effect and similar ones. I'll take a look at it in my deck builder project, to find a way to include this kind of behaviour in the "final" tool :)

**Comment by versvs** [comment]
I think this issue with card counting is solved in the latest version! :)

Thanks!
